# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodingChallange' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftDate'
  pod 'Kingfisher'
  # Pods for CodingChallange

  target 'CodingChallangeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
